from turtle import *
speed(-1)
shape("turtle")
color("red")
for i in range(4):
    left(30)
    forward(50)
    right(60)
    forward(50)
    right(120)
    forward(50)
    right(60)
    forward(50)
    left(120)
mainloop()